<a href="https://colab.research.google.com/github/muthonioprah/AutoLib-Dataset-Analysis/blob/main/Moringa_Data_Science_Prep_W4_Independent_Project_2021_11_Oprah_Muthoni_PythonProject.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Business Understanding**

In this week's independent project, you will be working as a data scientist working for an electric car-sharing service company. You have been tasked to process stations data to understand electric car usage over time by solving for the following research question;



*   Identify the most popular hour of the day for picking up a shared electric car (Bluecar) in the city of Paris over the month of April 2018


*   What is the most popular hour for returning cars?

*   What station is the most popular?
       Overall?
       At the most popular picking hour?

*  What postal code is the most popular for picking up Blue cars? Does the most popular station belong to that postal code?

*   Do the results change if you consider Utilib and Utilib 1.4 instead of Blue cars?

# **Data Understanding**
Doing this in order to understand the attributes of the data. Summarize the data by identifying key characteristics, such as data volume and total number of variables in the data. Understand the problems with the data, such as missing values, inaccuracies, and outliers

 **Importing the libraries needed for this project**

In [ ]:
# Importing the libraries we will need 

# Importing the pandas library
# 
import pandas as pd

# Importing the numpy library
#
import numpy as np

**Loading the dataset to be used**

In [ ]:
#to read the data in the csv file to create a dataframe
#the dataframe will be referred to as 'df1'
df1 = pd.read_csv('/content/Autolib_dataset (2).csv')
#to display the top 5 records of the dataframe
df1.head(5)

                              Address  Cars  Bluecar counter  ...  day  hour  minute
0                 2 Avenue de Suffren     0                0  ...    8    11      43
1           145 Rue Raymond Losserand     6                6  ...    6     7      24
2    2 Avenue John Fitzgerald Kennedy     3                3  ...    3    20      14
3              51 Rue EugÃ¨ne OudinÃ©     3                3  ...    4     4      37
4  6 avenue de la Porte de Champerret     3                3  ...    8    17      23

[5 rows x 25 columns]

In [ ]:
#getting information on the dataframe
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 25 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Address              5000 non-null   object
 1   Cars                 5000 non-null   int64
 2   Bluecar counter      5000 non-null   int64
 3   Utilib counter       5000 non-null   int64
 4   Utilib 1.4 counter   5000 non-null   int64
 5   Charge Slots         5000 non-null   int64
 6   Charging Status      5000 non-null   object
 7   City                 5000 non-null   object
 8   Displayed comment    111 non-null    object
 9   ID                   5000 non-null   object
 10  Kind                 5000 non-null   object
 11  Geo point            5000 non-null   object
 12  Postal code          5000 non-null   int64
 13  Public name          5000 non-null   object
 14  Rental status        5000 non-null   object
 15  Scheduled at         47 non-null     object
 16  Slots                5000 non-null   int64
 17  Station type         5000 non-null   object
 18  Status               5000 non-null   object
 19  Subscription status  5000 non-null   object
 20  year                 5000 non-null   int64
 21  month                5000 non-null   int64
 22  day                  5000 non-null   int64
 23  hour                 5000 non-null   int64
 24  minute               5000 non-null   int64
dtypes: int64(12), object(13)
memory usage: 976.7+ KB

In [ ]:
#to get the number of rows and columns respectively
df1.shape

(5000, 25)

In [ ]:
#to generate descriptive statistics of the DataFrame
df1.describe()

              Cars  Bluecar counter  ...         hour       minute
count  5000.000000      5000.000000  ...  5000.000000  5000.000000
mean      2.333600         2.333600  ...    11.509200    29.270000
std       2.035274         2.035274  ...     6.893549    17.231741
min       0.000000         0.000000  ...     0.000000     0.000000
25%       0.000000         0.000000  ...     6.000000    14.000000
50%       2.000000         2.000000  ...    11.000000    29.000000
75%       4.000000         4.000000  ...    18.000000    44.000000
max       7.000000         7.000000  ...    23.000000    59.000000

[8 rows x 12 columns]

In [ ]:
#to check null values in the DataFrame
df1.isnull()

      Address   Cars  Bluecar counter  ...    day   hour  minute
0       False  False            False  ...  False  False   False
1       False  False            False  ...  False  False   False
2       False  False            False  ...  False  False   False
3       False  False            False  ...  False  False   False
4       False  False            False  ...  False  False   False
...       ...    ...              ...  ...    ...    ...     ...
4995    False  False            False  ...  False  False   False
4996    False  False            False  ...  False  False   False
4997    False  False            False  ...  False  False   False
4998    False  False            False  ...  False  False   False
4999    False  False            False  ...  False  False   False

[5000 rows x 25 columns]

In [ ]:
#dropping rows where all data is missing
df1.dropna(how = "all")

                                 Address  Cars  ...  hour  minute
0                    2 Avenue de Suffren     0  ...    11      43
1              145 Rue Raymond Losserand     6  ...     7      24
2       2 Avenue John Fitzgerald Kennedy     3  ...    20      14
3                 51 Rue EugÃ¨ne OudinÃ©     3  ...     4      37
4     6 avenue de la Porte de Champerret     3  ...    17      23
...                                  ...   ...  ...   ...     ...
4995                 8 avenue MÃ©nelotte     2  ...    11      26
4996                   37 rue de Dantzig     4  ...    16      56
4997                      142 rue du Bac     1  ...     7       1
4998         2 avenue du Val de Fontenay     2  ...    17      27
4999                 5 Rue Henry Brisson     4  ...    10       2

[5000 rows x 25 columns]

#**Data Preparation**

In [ ]:
#to fill the null values with '0'
df1_cleaned = df1.fillna(0)
df1_cleaned

                                 Address  Cars  ...  hour  minute
0                    2 Avenue de Suffren     0  ...    11      43
1              145 Rue Raymond Losserand     6  ...     7      24
2       2 Avenue John Fitzgerald Kennedy     3  ...    20      14
3                 51 Rue EugÃ¨ne OudinÃ©     3  ...     4      37
4     6 avenue de la Porte de Champerret     3  ...    17      23
...                                  ...   ...  ...   ...     ...
4995                 8 avenue MÃ©nelotte     2  ...    11      26
4996                   37 rue de Dantzig     4  ...    16      56
4997                      142 rue du Bac     1  ...     7       1
4998         2 avenue du Val de Fontenay     2  ...    17      27
4999                 5 Rue Henry Brisson     4  ...    10       2

[5000 rows x 25 columns]

In [ ]:
#to review the cleaned dataframe
df1_cleaned

                                 Address  Cars  ...  hour  minute
0                    2 Avenue de Suffren     0  ...    11      43
1              145 Rue Raymond Losserand     6  ...     7      24
2       2 Avenue John Fitzgerald Kennedy     3  ...    20      14
3                 51 Rue EugÃ¨ne OudinÃ©     3  ...     4      37
4     6 avenue de la Porte de Champerret     3  ...    17      23
...                                  ...   ...  ...   ...     ...
4995                 8 avenue MÃ©nelotte     2  ...    11      26
4996                   37 rue de Dantzig     4  ...    16      56
4997                      142 rue du Bac     1  ...     7       1
4998         2 avenue du Val de Fontenay     2  ...    17      27
4999                 5 Rue Henry Brisson     4  ...    10       2

[5000 rows x 25 columns]

In [ ]:
#First to change the day, month and year column from int to objects
df1_cleaned['year'] = df1_cleaned['year'].astype(str)
df1_cleaned['month'] = df1_cleaned['month'].astype(str)
df1_cleaned['day'] = df1_cleaned['day'].astype(str)

#combining the  day, month and year column to form a date column
df1_cleaned['Date'] = df1_cleaned[['year', 'month', 'day']].agg('-'.join, axis=1) 
df1_cleaned

                                 Address  Cars  ...  minute      Date
0                    2 Avenue de Suffren     0  ...      43  2018-4-8
1              145 Rue Raymond Losserand     6  ...      24  2018-4-6
2       2 Avenue John Fitzgerald Kennedy     3  ...      14  2018-4-3
3                 51 Rue EugÃ¨ne OudinÃ©     3  ...      37  2018-4-4
4     6 avenue de la Porte de Champerret     3  ...      23  2018-4-8
...                                  ...   ...  ...     ...       ...
4995                 8 avenue MÃ©nelotte     2  ...      26  2018-4-6
4996                   37 rue de Dantzig     4  ...      56  2018-4-4
4997                      142 rue du Bac     1  ...       1  2018-4-1
4998         2 avenue du Val de Fontenay     2  ...      27  2018-4-4
4999                 5 Rue Henry Brisson     4  ...       2  2018-4-8

[5000 rows x 26 columns]

In [ ]:
#First to change the time and year column from int to objects
df1_cleaned['hour'] = df1_cleaned['hour'].astype(str)
df1_cleaned['minute'] = df1_cleaned['minute'].astype(str)
#to combine the two columns into one called time
df1_cleaned['Time'] = df1_cleaned[['hour', 'minute']].agg(':'.join, axis=1)
df1_cleaned

                                 Address  Cars  ...      Date   Time
0                    2 Avenue de Suffren     0  ...  2018-4-8  11:43
1              145 Rue Raymond Losserand     6  ...  2018-4-6   7:24
2       2 Avenue John Fitzgerald Kennedy     3  ...  2018-4-3  20:14
3                 51 Rue EugÃ¨ne OudinÃ©     3  ...  2018-4-4   4:37
4     6 avenue de la Porte de Champerret     3  ...  2018-4-8  17:23
...                                  ...   ...  ...       ...    ...
4995                 8 avenue MÃ©nelotte     2  ...  2018-4-6  11:26
4996                   37 rue de Dantzig     4  ...  2018-4-4  16:56
4997                      142 rue du Bac     1  ...  2018-4-1    7:1
4998         2 avenue du Val de Fontenay     2  ...  2018-4-4  17:27
4999                 5 Rue Henry Brisson     4  ...  2018-4-8   10:2

[5000 rows x 27 columns]

In [ ]:
#to combine the date and time columns
df1_cleaned['Date_Time'] = df1_cleaned[['Date', 'Time']].agg(' '.join, axis=1)
df1_cleaned

                                 Address  Cars  ...   Time       Date_Time
0                    2 Avenue de Suffren     0  ...  11:43  2018-4-8 11:43
1              145 Rue Raymond Losserand     6  ...   7:24   2018-4-6 7:24
2       2 Avenue John Fitzgerald Kennedy     3  ...  20:14  2018-4-3 20:14
3                 51 Rue EugÃ¨ne OudinÃ©     3  ...   4:37   2018-4-4 4:37
4     6 avenue de la Porte de Champerret     3  ...  17:23  2018-4-8 17:23
...                                  ...   ...  ...    ...             ...
4995                 8 avenue MÃ©nelotte     2  ...  11:26  2018-4-6 11:26
4996                   37 rue de Dantzig     4  ...  16:56  2018-4-4 16:56
4997                      142 rue du Bac     1  ...    7:1    2018-4-1 7:1
4998         2 avenue du Val de Fontenay     2  ...  17:27  2018-4-4 17:27
4999                 5 Rue Henry Brisson     4  ...   10:2   2018-4-8 10:2

[5000 rows x 28 columns]

In [ ]:
#now to convert the date column to datetime type
df1_cleaned['Date_Time'] = pd.to_datetime(df1_cleaned['Date_Time'])
df1_cleaned

                                 Address  Cars  ...   Time           Date_Time
0                    2 Avenue de Suffren     0  ...  11:43 2018-04-08 11:43:00
1              145 Rue Raymond Losserand     6  ...   7:24 2018-04-06 07:24:00
2       2 Avenue John Fitzgerald Kennedy     3  ...  20:14 2018-04-03 20:14:00
3                 51 Rue EugÃ¨ne OudinÃ©     3  ...   4:37 2018-04-04 04:37:00
4     6 avenue de la Porte de Champerret     3  ...  17:23 2018-04-08 17:23:00
...                                  ...   ...  ...    ...                 ...
4995                 8 avenue MÃ©nelotte     2  ...  11:26 2018-04-06 11:26:00
4996                   37 rue de Dantzig     4  ...  16:56 2018-04-04 16:56:00
4997                      142 rue du Bac     1  ...    7:1 2018-04-01 07:01:00
4998         2 avenue du Val de Fontenay     2  ...  17:27 2018-04-04 17:27:00
4999                 5 Rue Henry Brisson     4  ...   10:2 2018-04-08 10:02:00

[5000 rows x 28 columns]

In [ ]:
#To drop the separated date and time columns
df = df1_cleaned.drop(['Date', 'Time', 'year', 'month', 'day', 'hour', 'minute'], axis = 1)
df

                                 Address  ...           Date_Time
0                    2 Avenue de Suffren  ... 2018-04-08 11:43:00
1              145 Rue Raymond Losserand  ... 2018-04-06 07:24:00
2       2 Avenue John Fitzgerald Kennedy  ... 2018-04-03 20:14:00
3                 51 Rue EugÃ¨ne OudinÃ©  ... 2018-04-04 04:37:00
4     6 avenue de la Porte de Champerret  ... 2018-04-08 17:23:00
...                                  ...  ...                 ...
4995                 8 avenue MÃ©nelotte  ... 2018-04-06 11:26:00
4996                   37 rue de Dantzig  ... 2018-04-04 16:56:00
4997                      142 rue du Bac  ... 2018-04-01 07:01:00
4998         2 avenue du Val de Fontenay  ... 2018-04-04 17:27:00
4999                 5 Rue Henry Brisson  ... 2018-04-08 10:02:00

[5000 rows x 21 columns]

# **Data Analysis**

In [ ]:
#grouping the data based on the city
city = df.groupby('City')
city
#to get one of the groups which in this case is 'Paris'
paris = city.get_group('Paris')
paris

                                 Address  ...           Date_Time
0                    2 Avenue de Suffren  ... 2018-04-08 11:43:00
1              145 Rue Raymond Losserand  ... 2018-04-06 07:24:00
3                 51 Rue EugÃ¨ne OudinÃ©  ... 2018-04-04 04:37:00
4     6 avenue de la Porte de Champerret  ... 2018-04-08 17:23:00
5                   8 Boulevard Voltaire  ... 2018-04-06 07:02:00
...                                  ...  ...                 ...
4992                     3 avenue d'Ivry  ... 2018-04-09 23:01:00
4994                    15 rue de Rocroy  ... 2018-04-01 20:49:00
4996                   37 rue de Dantzig  ... 2018-04-04 16:56:00
4997                      142 rue du Bac  ... 2018-04-01 07:01:00
4999                 5 Rue Henry Brisson  ... 2018-04-08 10:02:00

[2816 rows x 21 columns]

In [ ]:
#filter only the rows where the blue counter cars in paris are greater than 0
blue_paris = paris.loc[paris['Bluecar counter'] > 0]
blue_paris

                                 Address  ...           Date_Time
1              145 Rue Raymond Losserand  ... 2018-04-06 07:24:00
3                 51 Rue EugÃ¨ne OudinÃ©  ... 2018-04-04 04:37:00
4     6 avenue de la Porte de Champerret  ... 2018-04-08 17:23:00
8                  34 avenue Jean Moulin  ... 2018-04-02 22:58:00
9           41 boulevard de Rochechouart  ... 2018-04-04 15:02:00
...                                  ...  ...                 ...
4985     6 place du PrÃ©sident Mithouard  ... 2018-04-04 02:35:00
4988                        62 Rue Ramey  ... 2018-04-08 11:00:00
4996                   37 rue de Dantzig  ... 2018-04-04 16:56:00
4997                      142 rue du Bac  ... 2018-04-01 07:01:00
4999                 5 Rue Henry Brisson  ... 2018-04-08 10:02:00

[1787 rows x 21 columns]

In [ ]:
#Now to find only the records in the month of April 2018
april = (blue_paris['Date_Time'] > '2018-03-31') & (blue_paris['Date_Time'] <= '2018-04-30')

In [ ]:
#now to narrow down to the stations operational for renting.
rentable = (blue_paris['Rental status'] == 'operational')

In [ ]:
#the stations should also be available to charge since we are dealing with electric cars
chargable = (blue_paris['Charging Status'] =='operational')

In [ ]:
#the stations should be a station
station = (blue_paris['Kind'] =='STATION')

In [ ]:
#to make sure the dataframe we are left with fits these conditions
blue_paris[april & rentable & chargable & station]

                              Address  ...           Date_Time
1           145 Rue Raymond Losserand  ... 2018-04-06 07:24:00
3              51 Rue EugÃ¨ne OudinÃ©  ... 2018-04-04 04:37:00
17             182 Boulevard Voltaire  ... 2018-04-09 12:14:00
19               11 avenue RenÃ© Coty  ... 2018-04-09 21:31:00
24         15 avenue Ãmile Deschanel  ... 2018-04-04 23:27:00
...                               ...  ...                 ...
4985  6 place du PrÃ©sident Mithouard  ... 2018-04-04 02:35:00
4988                     62 Rue Ramey  ... 2018-04-08 11:00:00
4996                37 rue de Dantzig  ... 2018-04-04 16:56:00
4997                   142 rue du Bac  ... 2018-04-01 07:01:00
4999              5 Rue Henry Brisson  ... 2018-04-08 10:02:00

[1243 rows x 21 columns]

In [ ]:
# Now to check the most repeated date which will be the most common time to hire a bluecar
#value_counts - counts the date values
#idmax() - find the most repeated value from the counted date
popular_time = blue_paris['Date_Time']. value_counts(). idxmax()
print(str(popular_time) + ' is the most popular time to hire a blue car in Paris')

2018-04-05 14:48:00 is the most popular time to hire a blue car in Paris

**What is the most popular hour for returning cars?**
> assuming that where cars are returned is where they are parked. This means that there should be more than one parking space and the kind of station should be a parking station.

In [ ]:
#To find the stations with more than '0' parking slots
slots = (blue_paris['Slots'] > 0)
#the kind of station should be parking
parking = (blue_paris['Kind'] == 'PARKING')
blue_paris1 = blue_paris[april & rentable & slots & parking]
blue_paris1

                                 Address  ...           Date_Time
4     6 avenue de la Porte de Champerret  ... 2018-04-08 17:23:00
208                26 villa Croix-Nivert  ... 2018-04-08 03:44:00
393                       2 place Joffre  ... 2018-04-05 01:40:00
581               65 boulevard de Picpus  ... 2018-04-04 23:41:00
637                 38 avenue des Ternes  ... 2018-04-08 21:06:00
709                    81 rue FalguiÃ¨re  ... 2018-04-07 03:53:00
758                        1 rue Velpeau  ... 2018-04-04 21:00:00
845                 38 avenue des Ternes  ... 2018-04-01 09:12:00
963                     2 avenue Gabriel  ... 2018-04-05 14:48:00
982                26 villa Croix-Nivert  ... 2018-04-01 21:19:00
1088  6 avenue de la Porte de Champerret  ... 2018-04-01 06:25:00
1150                   81 rue FalguiÃ¨re  ... 2018-04-09 17:31:00
1373         171 boulevard Saint-Germain  ... 2018-04-04 18:39:00
1467               26 villa Croix-Nivert  ... 2018-04-01 05:51:00
1577      26 boulevard Gouvion Saint-Cyr  ... 2018-04-02 15:26:00
1819         171 boulevard Saint-Germain  ... 2018-04-06 09:32:00
1887                    141 rue Lecourbe  ... 2018-04-04 17:57:00
1905    2 avenue de la Porte Saint-Cloud  ... 2018-04-03 03:38:00
2158              65 boulevard de Picpus  ... 2018-04-05 03:11:00
2193        41 boulevard de Rochechouart  ... 2018-04-03 00:49:00
2245         171 boulevard Saint-Germain  ... 2018-04-07 08:06:00
2360       1 avenue du GÃ©nÃ©ral Sarrail  ... 2018-04-05 13:16:00
2453                38 avenue des Ternes  ... 2018-04-01 23:25:00
2641                    2 avenue Gabriel  ... 2018-04-03 22:01:00
3031                168 bis rue Cardinet  ... 2018-04-08 11:07:00
3033        41 boulevard de Rochechouart  ... 2018-04-02 11:56:00
3101         171 boulevard Saint-Germain  ... 2018-04-02 16:44:00
3249                   21 Rue Abel Gance  ... 2018-04-08 03:05:00
3331              65 boulevard de Picpus  ... 2018-04-04 05:03:00
3470                      2 place Joffre  ... 2018-04-08 00:46:00
3684  6 avenue de la Porte de Champerret  ... 2018-04-07 11:02:00
3704  6 avenue de la Porte de Champerret  ... 2018-04-07 10:25:00
3812                      2 place Joffre  ... 2018-04-01 21:14:00
3898                   81 rue FalguiÃ¨re  ... 2018-04-05 05:27:00
4014        1 place du parvis Notre-Dame  ... 2018-04-04 09:48:00
4026                      2 place Joffre  ... 2018-04-02 00:01:00
4095                       1 rue Velpeau  ... 2018-04-01 07:54:00
4529                       1 rue Velpeau  ... 2018-04-07 12:36:00

[38 rows x 21 columns]

In [ ]:
#find the popular return time
popular_return = blue_paris1['Date_Time']. value_counts(). idxmax()
print(str(popular_return) + ' is the most popular time to return a blue car in Paris')

2018-04-02 11:56:00 is the most popular time to return a blue car in Paris

**What station is the most popular bluecar station?**


>1.overall

In [ ]:
#themost popular station for blue cars overall
popular_station = blue_paris['Public name']. value_counts(). idxmax()
print(str(popular_station) + " is the most popular station overall for blue cars")

Paris/Porte de Montrouge/8 is the most popular station overall for blue cars

2. At the most popular picking hour

In [ ]:
#to locate the popular time
pop_station = blue_paris.loc[blue_paris['Date_Time'] =='2018-04-05 14:48:00']
pop_station
popular_station1 = pop_station['Public name']. value_counts(). idxmax()
print(str(popular_station1) + " is the most popular station at the most popular picking hour")

Paris/Victor MassÃ©/35 is the most popular station at the most popular picking hour